CREATE OR REPLACE TYPE T_BANK_LIST_ITEM AS OBJECT
(
  ALETERNATIVE_RULE_PAYSYS VARCHAR2(50),
  ALETERNATIVE_ACCOUNT VARCHAR2(50),
  ALETERNATIVE_SWIFT VARCHAR2(100),
  CORR_SUB VARCHAR2(100),
  PARENT_CODE VARCHAR2(100),
  PARENT_ID INTEGER,
  VOEN VARCHAR2(100),
  CORR_ACC VARCHAR2(100),
  BANK_CODE VARCHAR2(100),
  BANK_NAME VARCHAR2(500),
  BANK_SWIFT VARCHAR2(10),
  ID INTEGER
)
/
