create or replace type T_MESSAGE_STRUCT_304 FORCE UNDER T_MESSAGE_STRUCT
(
    MEMBER FUNCTION GET_HEADER_BLOCK1(SELF IN OUT T_MESSAGE_STRUCT_304) RETURN VARCHAR,
    MEMBER FUNCTION GET_HEADER_BLOCK2(SELF IN OUT T_MESSAGE_STRUCT_304) RETURN VARCHAR,
    MEMBER FUNCTION GET_HEADER_BLOCK4(SELF IN OUT T_MESSAGE_STRUCT_304, l_body VARCHAR2) RETURN VARCHAR,
    MEMBER FUNCTION GET_HEADER_BLOCK5(SELF IN OUT T_MESSAGE_STRUCT_304, l_body VARCHAR2) RETURN VARCHAR,
    MEMBER FUNCTION GET_BATCHES_NUM(SELF IN OUT T_MESSAGE_STRUCT_304) RETURN INTEGER,
    MEMBER FUNCTION GET_MESSAGE_EMITENT_BANK(SELF IN OUT T_MESSAGE_STRUCT_304) RETURN VARCHAR,
    MEMBER FUNCTION GET_MESSAGE_RECEIVER_BANK(SELF IN OUT T_MESSAGE_STRUCT_304) RETURN VARCHAR,
    MEMBER FUNCTION GET_MESSAGE_TYPE(SELF IN OUT T_MESSAGE_STRUCT_304) RETURN VARCHAR,
    OVERRIDING MEMBER FUNCTION COMPLETE(SELF IN OUT T_MESSAGE_STRUCT_304) RETURN BOOLEAN,
    OVERRIDING MEMBER FUNCTION GET_FILE_EXTENSION RETURN VARCHAR2,
    OVERRIDING MEMBER PROCEDURE GENERATE_CONTENT,
    CONSTRUCTOR FUNCTION T_MESSAGE_STRUCT_304 RETURN SELF AS RESULT
) NOT FINAL
/
create or replace type body T_MESSAGE_STRUCT_304 IS

    MEMBER FUNCTION GET_BATCHES_NUM(SELF IN OUT T_MESSAGE_STRUCT_304) RETURN INTEGER IS
    BEGIN RETURN 1; END;
    
    MEMBER FUNCTION GET_MESSAGE_EMITENT_BANK(SELF IN OUT T_MESSAGE_STRUCT_304) RETURN VARCHAR IS
    BEGIN RETURN '***** EMITENT IBAN *****'; END;
    
    MEMBER FUNCTION GET_MESSAGE_RECEIVER_BANK(SELF IN OUT T_MESSAGE_STRUCT_304) RETURN VARCHAR IS
    BEGIN RETURN '***** RECEIVER IBAN *****'; END;
    
    MEMBER FUNCTION GET_MESSAGE_TYPE(SELF IN OUT T_MESSAGE_STRUCT_304) RETURN VARCHAR IS
    BEGIN RETURN SELF.obj.MESSAGE_TYPE; END;

    OVERRIDING MEMBER FUNCTION COMPLETE(SELF IN OUT T_MESSAGE_STRUCT_304) RETURN BOOLEAN IS 
        l_result    BOOLEAN DEFAULT FALSE;
        l_date      DATE DEFAULT SYSDATE;
    BEGIN
        l_result := (SELF AS T_MESSAGE_STRUCT).COMPLETE;
        RETURN FALSE;
    END;
    
    OVERRIDING MEMBER FUNCTION GET_FILE_EXTENSION RETURN VARCHAR2 IS BEGIN RETURN '.nps'; END;

    MEMBER FUNCTION GET_HEADER_BLOCK1(SELF IN OUT T_MESSAGE_STRUCT_304) RETURN VARCHAR IS
    BEGIN
        RETURN '{1:F01' || GET_MESSAGE_EMITENT_BANK() || SELF.obj.EMITENT_BANK_TAX || '}';
    END;
    
    MEMBER FUNCTION GET_HEADER_BLOCK2(SELF IN OUT T_MESSAGE_STRUCT_304) RETURN VARCHAR IS
    BEGIN
        RETURN '{2:I'|| GET_MESSAGE_TYPE || GET_MESSAGE_RECEIVER_BANK() || 'N}';
    END;
    
    MEMBER FUNCTION GET_HEADER_BLOCK5(SELF IN OUT T_MESSAGE_STRUCT_304, l_body VARCHAR2) RETURN VARCHAR IS
    BEGIN
        RETURN '{5:{MAC:'|| ext_serv.cbar.sing(l_body) || '}}';
    END;
    
    MEMBER FUNCTION GET_HEADER_BLOCK4(SELF IN OUT T_MESSAGE_STRUCT_304, l_body VARCHAR2) RETURN VARCHAR IS
    BEGIN RETURN '{4:' || SELF.tag_ln || SELF.smart_ln(l_body) || '-}'; END;
    
    OVERRIDING MEMBER PROCEDURE GENERATE_CONTENT IS
        l_body CLOB DEFAULT SELF.GENERATE_BODY;
    BEGIN
        SELF.SOURCE_CONTENT := chr(1) || SELF.GET_HEADER_BLOCK1() 
                                || GET_HEADER_BLOCK2() 
                                || SELF.GET_HEADER_BLOCK4(l_body) 
                                --|| SELF.GET_HEADER_BLOCK5(l_body)
                                || chr(3);
    END;

    -- Member procedures and functions
    CONSTRUCTOR FUNCTION T_MESSAGE_STRUCT_304 RETURN SELF AS RESULT 
    IS BEGIN RETURN; END;
  
end;
/
